# Generated by Django 4.2.4 on 2023-08-13 11:01

from django.db import migrations, models
import src.goods.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.CharField(default='Пусто', max_length=150, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to=src.goods.models.user_directory_path, verbose_name='Фото товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
